name: Deploy

on:
  workflow_call:
    input:
      artifact:
        required: true
        type: string
    outputs:
      artifact:
        description: The Name Of The Artifact
        value: ${{ jobs.build.outputs.artifact }}

env:
  VERSION: ${{ github.sha }}  
  VITE_SENTRY_RELEASE: ${{ github.sha }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    outputs:
      artifact: ${{ steps.output.outputs.artifact }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3 

      - name: Set Up Node
        uses: actions/setup-node@v3
        with:
          cache: npm

      - name: Install
        run: npm ci --force

      - name: Build
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ input.artifact }}
          path: dist
          if-no-files-found: error
          retention-days: 5

      - name: Output Artifact Name
        id: output
        run: echo "artifact=${{ input.artifact }}" >> $GITHUB_OUTPUT
