name: Commit Stage

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    uses: ./.github/workflows/commit-stage--build-artifact.yml
    with:
      artifact: ${{ github.event.repository.name }}
      version: ${{ github.sha }}

  eslint:
    name: ESLint
    uses: ./.github/workflows/commit-stage--run-eslint-on-code.yml

  analyze:
    name: Analyze
    uses: ./.github/workflows/commit-stage--sonarcloud-analyze-code.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  upload:
    needs: [build]
    name: Upload
    uses: ./.github/workflows/commit-stage--upload-image-to-scaleway-registry.yml
    with:
      image: ${{ needs.build.outputs.artifact }}
      artifact: ${{ needs.build.outputs.artifact }}
      version: ${{ needs.build.outputs.version }}
    secrets:
      SCW_DOCKER_REGISTRY: ${{ secrets.SCW_DOCKER_REGISTRY }}
      SCW_TOKEN: ${{ secrets.SCW_TOKEN }}

  check:
    needs: [analyze]
    name: Check
    uses: ./.github/workflows/commit-stage--query-quality-gate-status.yml
    with:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
