name: Deploy

on:
  push:
    branches:
      - main

env:
  VERSION: ${{ github.sha }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  VITE_SENTRY_RELEASE: ${{ github.sha }}

jobs:
  sentry:
    name: Create A Sentry Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3 
        with:
          fetch-depth: 0

      - name: Set Up Node
        uses: actions/setup-node@v3

      - name: Install Deps
        run: npm install

      - name: Build
        run: npm run build

      - name: Create A Sentry Release
        run: |
          sentry-cli --url https://sentry.law-orga.de releases --org sentry --project lawandorga-main-frontend new "$VERSION"
          sentry-cli --url https://sentry.law-orga.de releases --org sentry --project lawandorga-main-frontend set-commits "$VERSION" --auto
          sentry-cli --url https://sentry.law-orga.de releases --org sentry --project lawandorga-main-frontend files "$VERSION" upload-sourcemaps dist

      - name: Publish To Netlify
        run: netlify deploy --dir=dist --prod

      - name: Finalize And Deploy A Sentry Release
        run: |
          sentry-cli --url https://sentry.law-orga.de releases --org sentry --project lawandorga-main-frontend finalize "$VERSION"
          sentry-cli --url https://sentry.law-orga.de releases --org sentry --project lawandorga-main-frontend deploys "$VERSION" new -e production
