name: Deploy To Scaleway Bucket

on: 
  workflow_call:
    secrets:
      bucket:
        required: true
      artifact:
        required: true
      S3_ACCESS_TOKEN:
        required: true
      S3_SECRET_KEY:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3 
        with:
          fetch-depth: 0

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact }}
          path: dist

      - name: Install AWS Cli Dependencies
        run: pip3 install awscli awscli-plugin-endpoint

      - name: Configure AWS Cli
        run: |
          aws configure set plugins.endpoint awscli_plugin_endpoint
          aws configure << EOF
          ${{ secrets.S3_ACCESS_TOKEN }}
          ${{ secrets.S3_SECRET_KEY }}
          fr-par

          EOF

      - name: Upload To S3
        run: aws s3 cp dist s3://lawandorga-main-frontend --recursive --endpoint-url https://s3.fr-par.scw.cloud --region fr-par
