name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build-artifact.yml
    with:
      artifact: lawandorga-main-frontend-build
      version: ${{ github.sha }}

  job2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo ${{ needs.build.outputs.artifact }} ${{ needs.build.outputs.version }}

  deploy:
    needs: [build]
    name: Deploy To Scaleway
    uses: ./.github/workflows/deploy-to-scaleway-bucket.yml
    with:
      artifact: ${{ needs.build.outputs.artifact }}
      bucket: lawandorga-main-frontend
    secrets:
      S3_ACCESS_TOKEN: ${{ secrets.S3_ACCESS_TOKEN }}
      S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}

  sentry:
    needs: [build, deploy]
    name: Create A Sentry Release
    uses: ./.github/workflows/create-a-sentry-release.yml
    with:
      version: ${{ needs.build.outputs.version }}
      artifact: ${{ needs.build.outputs.artifact }}
      project: lawandorga-main-frontend
      org: sentry
    secrets:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
