name: Deployment Stage - Create A Release For Sentry

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      artifact:
        required: true
        type: string
      project:
        required: true
        type: string
      org:
        required: true
        type: string
    secrets:
      SENTRY_AUTH_TOKEN:
        required: true

jobs:
  deploy:
    name: Create Release
    runs-on: ubuntu-22.04

    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: ${{ inputs.artifact }}
          path: dist

      - name: Install Sentry CLI
        run: curl -sL https://sentry.io/get-cli/ | bash

      - name: Create A Sentry Release
        run: |
          sentry-cli --url https://sentry.law-orga.de releases --org ${{ inputs.org }} --project ${{ inputs.project }} new "${{ inputs.version }}"
          sentry-cli --url https://sentry.law-orga.de releases --org ${{ inputs.org }} --project ${{ inputs.project }} set-commits "${{ inputs.version }}" --auto
          sentry-cli --url https://sentry.law-orga.de releases --org ${{ inputs.org }} --project ${{ inputs.project }} files "${{ inputs.version }}" upload-sourcemaps dist
          sentry-cli --url https://sentry.law-orga.de releases --org ${{ inputs.org }} --project ${{ inputs.project }} finalize "${{ inputs.version }}"
          sentry-cli --url https://sentry.law-orga.de releases --org ${{ inputs.org }} --project ${{ inputs.project }} deploys "${{ inputs.version }}" new -e production
