name: Deploy

on:
  push:
    branches:
      - main

env:
  VERSION: ${{ github.sha }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  sentry:
    name: Create A Sentry Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      # - name: Install Sentry CLI
      #   run: curl -sL https://sentry.io/get-cli/ | bash

      # - name: Create A Sentry Release
      #   run: | 
      #     sentry-cli --url https://sentry.law-orga.de releases --org sentry --project lawandorga-main-frontend new "$VERSION"
      #     sentry-cli --url https://sentry.law-orga.de releases --org sentry --project lawandorga-main-frontend finalize "$VERSION"

      - name: Sentry Release
        uses: getsentry/action-release@v1.2.1
        env:
          SENTRY_URL: https://sentry.law-orga.de
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: sentry
          SENTRY_PROJECT: lawandorga-main-frontend
        with:
          # environment: production
          ignore_missing: true
