name: Deployment Stage

on:
  workflow_run:
    workflows: ["Commit Stage"]
    types: [completed]

jobs:
  check:
    name: Check
    uses: ./.github/workflows/commit-stage--query-quality-gate-status.yml
    with:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    name: Deploy
    needs: [check]
    uses: ./.github/workflows/deployment-stage--terraform-apply.yml
    secrets:
      scw_access_key: ${{ secrets.SCW_ACCESS_KEY }}
      scw_project_id: ${{ secrets.SCW_PROJECT_ID }}
      scw_secret_key: ${{ secrets.SCW_SECRET_KEY }}

  sentry:
    name: Sentry
    needs: [check]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/deployment-stage--create-a-sentry-release.yml
    with:
      artifact: ${{ github.event.repository.name }}
      version: ${{ github.sha }}
      project: lawandorga-main-frontend
      org: sentry
    secrets:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
