name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build-artifact.yml
    with:
      artifact: lawandorga-main-frontend-build
      version: ${{ github.sha }}

  deploy:
    needs: [build]
    name: Deploy
    uses: ./.github/workflows/deploy-to-scaleway-bucket.yml
    with:
      artifact: ${{ needs.build.outputs.artifact }}
      bucket: www.law-orga.de
    secrets:
      S3_ACCESS_TOKEN: ${{ secrets.S3_ACCESS_TOKEN }}
      S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}

  sentry:
    needs: [build, deploy]
    name: Sentry
    uses: ./.github/workflows/create-a-sentry-release.yml
    with:
      version: ${{ needs.build.outputs.version }}
      artifact: ${{ needs.build.outputs.artifact }}
      project: lawandorga-main-frontend
      org: sentry
    secrets:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
