name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build-artifact.yml
    with:
      artifact: ${{ github.event.repository.name }}
      version: ${{ github.sha }}

  upload:
    needs: [build]
    name: Upload
    uses: ./.github/workflows/upload-image-to-scaleway-registry.yml
    with:
      image: ${{ needs.build.outputs.artifact }}
      artifact: ${{ needs.build.outputs.artifact }}
      version: ${{ needs.build.outputs.version }}
    secrets:
      SCW_DOCKER_REGISTRY: ${{ secrets.SCW_DOCKER_REGISTRY }}
      SCW_TOKEN: ${{ secrets.SCW_TOKEN }}

  deploy:
    needs: [build, upload]
    name: Deploy
    uses: ./.github/workflows/trigger-container-redeploy-on-scaleway.yml
    with: 
      image: ${{ needs.build.outputs.artifact }}
      version: ${{ needs.build.outputs.version }}
      port: 8080
    secrets:
      SCW_DOCKER_REGISTRY: ${{ secrets.SCW_DOCKER_REGISTRY }}
      SCW_TOKEN: ${{ secrets.SCW_TOKEN }}
      SCW_CONTAINER_ID: ${{ secrets.SCW_CONTAINER_ID }}

  sentry:
    needs: [build, upload]
    name: Sentry
    uses: ./.github/workflows/create-a-sentry-release.yml
    with:
      version: ${{ needs.build.outputs.version }}
      artifact: ${{ needs.build.outputs.artifact }}
      project: lawandorga-main-frontend
      org: sentry
    secrets:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

  analyze:
    name: Analyze
    uses: ./.github/workflows/sonarcloud-analyze-code.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
