name: Other - Redeploy Container On Scaleway

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      port:
        required: false
        type: number
        default: 80
      version:
        required: false
        type: string
        default: latest
    secrets:
      SCW_CONTAINER_ID:
        required: true
      SCW_TOKEN:
        required: true
      SCW_DOCKER_REGISTRY:
        required: true

jobs:
  deploy:
    name: Redeploy Container
    runs-on: ubuntu-22.04
    steps:
      - name: Trigger A Redeploy
        run: |
          curl -X PATCH --fail-with-body \
            https://api.scaleway.com/containers/v1beta1/regions/fr-par/containers/${{ secrets.SCW_CONTAINER_ID }}/ \
            -H 'X-Auth-Token: ${{ secrets.SCW_TOKEN }}' \
            -H 'Content-Type: application/json' \
            -d '{ "redeploy": true, "registry_image": "${{ secrets.SCW_DOCKER_REGISTRY }}/${{ inputs.image }}:${{ inputs.version }}", "port": ${{ inputs.port }} }'
