name: Pull

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/run-eslint-on-code.yml

  analyze:
    name: Analyze
    uses: ./.github/workflows/sonarcloud-analyze-code.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
