name: Deploy

on: 
  workflow_call:
    input:
      image:
        required: true
        type: string
    secrets:
      SCW_CONTAINER_ID:
        required: true
      SCW_TOKEN:
        required: true


jobs:
  deploy:
    name: Redeploy Container
    runs-on: ubuntu-22.04
    steps:
      - name: Trigger A Redeploy
        run: |
          curl -X PATCH --fail-with-body \
            https://api.scaleway.com/containers/v1beta1/regions/fr-par/containers/${{ secrets.SCW_CONTAINER_ID }}/ \
            -H 'X-Auth-Token: ${{ secrets.SCW_TOKEN }}' \
            -H 'Content-Type: application/json' \
            -d '{ "redeploy": true, "registry_image": "${{ secrets.image }}:latest" }'
